# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-23 02:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='biaoti')),
                ('href', models.URLField(verbose_name='lianjie')),
                ('status', models.PositiveIntegerField(choices=[(1, 'normal'), (0, 'delete')], default=1, verbose_name='zhuangtai')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='quanzhong he shunxu', verbose_name='quanzhong')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='zuozhe')),
            ],
            options={
                'verbose_name': 'you lian',
                'verbose_name_plural': 'you lian',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='biaoti')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'html'), (2, 'latest'), (3, 'hottest'), (4, 'recent')], default=1, verbose_name='zhanshi leixing')),
                ('content', models.CharField(blank=True, help_text='if setting is not html, empty', max_length=500, verbose_name='neirong')),
                ('status', models.PositiveIntegerField(choices=[(1, 'zhanshi'), (0, 'Hidden')], default=1, verbose_name='Zhuangtai')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='zuozhe')),
            ],
            options={
                'verbose_name': 'ce bian lan',
                'verbose_name_plural': 'ce bian lan',
            },
        ),
    ]
